version: "3"

services:
  web:
    restart: always
    build: ./laravel
    volumes:
      - ./laravel:/var/www/
  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
